# Generated by Django 4.1.1 on 2022-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansmodel',
            name='price',
            field=models.CharField(default='00.0', max_length=50),
        ),
    ]
